apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynapp-deploy
  labels:
    app: mynapp-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2    
      maxSurge: 2
  minReadySeconds: 20      
  replicas: 1
  selector:
    matchLabels:
      app: mynapp-deploy
  template:
    metadata:
      labels:
        app: mynapp-deploy
    spec:
      containers:
        - image: c1t1d0s7/myweb
          name: mynapp
          ports:
          - containerPort: 8080
